apiVersion: v1
kind: Secret
metadata:
  name: top-members-secrets
type: Opaque
stringData:
  POSTGRES_DB: saramsg
  POSTGRES_USER: saramsg
  POSTGRES_PASSWORD: secret
  DATABASE_URL: postgres://saramsg:secret@postgres:5432/saramsg
  MEMBERSHIP_PASSCODE: "stop the war on gaza"
  SESSION_SECRET: "change-this-to-a-random-secret"
